name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
env:
  REGISTRY: "your-registry-container-url"
  IMAGE_NAME: "your-docker-image-name"
  USER_NAME: "User-name"
  PASSWORD_TOKEN: "TOKEN"
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
        
      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .
      
      - name: Remove all old images
        run: docker image prune -a -f
        
      - name: Login to docker registry
        run: docker login $REGISTRY -u $USER_NAME -p $PASSWORD_TOKEN
        
      - name: Push image to Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
        
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    
    steps:
      - name: Deploy Production Sever via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: IMAGE_NAME,REGISTRY,{{ secrets.ACCESS_TOKEN }},GITHUB_SHA
          script: |
            # Login to registry
            docker login -u $USER_NAME -p $PASSWORD_TOKEN $REGISTRY
            # Stop running container
            docker stop $(echo $IMAGE_NAME)
            # Remove old container
            docker rm $(echo $IMAGE_NAME)
            # Run a new container from a new image
            docker run -d \
            --restart always \
            --name $(echo $IMAGE_NAME) \
            $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)